version: "3"
services:
  db:
    image: "mysql:5.7"
    container_name: "local-voucher-app-mysql"
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'students_record'
      MYSQL_USER: 'students'
      MYSQL_PASSWORD: '5Tud3nt5*'
      MYSQL_ROOT_PASSWORD: '5Tud3nt5*'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
